CREATE TABLE `webdav_callbacks` (
  `callbackid` mediumint(15) NOT NULL AUTO_INCREMENT,
  `webdavid` int(11) NOT NULL DEFAULT '0',
  `uid` int(11) NOT NULL DEFAULT '0',
  `clientid` mediumint(15) NOT NULL DEFAULT '0',
  `url` varchar(255) NOT NULL DEFAULT '',
  `fields` mediumint,
  `created` int(11) NOT NULL DEFAULT '0',
  `called` int(11) NOT NULL DEFAULT '0',
  `deleted` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`callbackid`),
  KEY `SEARCH` (`webdavid`,`uid`,`clientid`,`created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `webdav_clients` (
  `clientid` mediumint(15) NOT NULL AUTO_INCREMENT,
  `webdavid` int(11) NOT NULL DEFAULT '0',
  `uid` int(11) NOT NULL DEFAULT '0',
  `api-url` varchar(255) NOT NULL DEFAULT '',
  `api-calls` int(11) NOT NULL DEFAULT '0',
  `api-response` int(11) NOT NULL DEFAULT '0',
  `api-result` mediumtext,
  `api-errors` int(11) NOT NULL DEFAULT '0',
  `api-errored` int(11) NOT NULL DEFAULT '0',
  `username` varchar(45) NOT NULL DEFAULT '',
  `password` varchar(32) NOT NULL DEFAULT '',
  `email` varchar(196) NOT NULL DEFAULT '',
  `name` varchar(64) NOT NULL DEFAULT '',
  `staging-file` varchar(64) NOT NULL DEFAULT '',
  `created` int(11) NOT NULL DEFAULT '0',
  `staged` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`clientid`),
  KEY `SEARCH` (`webdavid`,`uid`,`username`,`password`,`staging-file`,`staged`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `webdav_files` (
  `fileid` mediumint(42) NOT NULL AUTO_INCREMENT,
  `folderid` mediumint(32) NOT NULL DEFAULT '0',
  `webdavid` int(11) NOT NULL DEFAULT '0',
  `uid` int(11) NOT NULL DEFAULT '0',
  `key` varchar(32) NOT NULL DEFAULT '',
  `type` enum('script','image','data','unknown') NOT NULL DEFAULT 'unknown',
  `commonality-key` varchar(32) NOT NULL DEFAULT '',
  `releases-hashinfo` varchar(32) NOT NULL DEFAULT '',
  `fingerprint` varchar(44) NOT NULL DEFAULT '',
  `path` varchar(255) NOT NULL DEFAULT '',
  `filename` varchar(128) NOT NULL DEFAULT '',
  `mime-type` varchar(64) NOT NULL DEFAULT '',
  `extension` varchar(32) NOT NULL DEFAULT '',
  `bytes` int(11) NOT NULL DEFAULT '0',
  `bytes-edited` int(11) NOT NULL DEFAULT '0',
  `found` int(11) NOT NULL DEFAULT '0',
  `fingerprinted` int(11) NOT NULL DEFAULT '0',
  `shipped` int(11) NOT NULL DEFAULT '0',
  `edited` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`fileid`),
  KEY `SEARCH` (`folderid`,`webdavid`,`uid`,`key`,`commonality-key`,`type`,`releases-hashinfo`,`fingerprint`,`path`,`filename`,`mime-type`,`extension`,`found`,`fingerprinted`,`shipped`,`edited`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `webdav_folders` (
  `folderid` mediumint(32) NOT NULL AUTO_INCREMENT,
  `parent_fid` mediumint(32) NOT NULL,
  `webdavid` int(11) NOT NULL,
  `uid` int(11) NOT NULL DEFAULT '0',
  `key` varchar(32) NOT NULL DEFAULT '',
  `renegading` enum('Yes','No') NOT NULL DEFAULT 'No',
  `academic-license` enum('Yes','No') NOT NULL DEFAULT 'No',
  `license-key` varchar(32) NOT NULL DEFAULT '',
  `commonality-key` varchar(32) NOT NULL DEFAULT '',
  `releases-hashinfo` varchar(32) NOT NULL DEFAULT '',
  `primary` varchar(64) NOT NULL DEFAULT '',
  `path` varchar(255) NOT NULL DEFAULT '',
  `fingerprint` varchar(44) NOT NULL DEFAULT '',
  `folders` int(11) NOT NULL DEFAULT '0',
  `deleted` int(11) NOT NULL DEFAULT '0',
  `renegade` int(11) NOT NULL DEFAULT '0',
  `files` int(11) NOT NULL DEFAULT '0',
  `edited` int(11) NOT NULL DEFAULT '0',
  `bytes-files` mediumint(24) NOT NULL DEFAULT '0',
  `bytes-deleted` mediumint(24) NOT NULL DEFAULT '0',
  `bytes-renegade` mediumint(24) NOT NULL DEFAULT '0',
  `bytes-edited` mediumint(24) NOT NULL DEFAULT '0',
  `created` int(11) NOT NULL DEFAULT '0',
  `hunted` int(11) NOT NULL DEFAULT '0',
  `fingerprinted` int(11) DEFAULT '0',
  PRIMARY KEY (`folderid`),
  KEY `SEARCH` (`parent_fid`,`webdavid`,`key`,`commonality-key`,`fingerprint`,`primary`,`folders`,`deleted`,`renegade`,`files`,`hunted`,`created`,`fingerprinted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `webdav_webdavs` (
  `webdavid` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NOT NULL DEFAULT '0',
  `key` varchar(32) NOT NULL DEFAULT '',
  `clients` int(11) NOT NULL DEFAULT '0',
  `client-apis` int(11) NOT NULL DEFAULT '0',
  `username` varchar(45) NOT NULL DEFAULT '',
  `hashinfo` varchar(15) NOT NULL DEFAULT '',
  `hostname` varchar(255) NOT NULL DEFAULT '',
  `path` varchar(255) NOT NULL DEFAULT '',
  `htpasswd-file` varchar(128) NOT NULL DEFAULT '',
  `apache2-config` varchar(128) NOT NULL DEFAULT '',
  `awstats-config` varchar(128) NOT NULL DEFAULT '',
  `apache2-config-updated` int(11) NOT NULL DEFAULT '0',
  `awstats-config-updated` int(11) NOT NULL DEFAULT '0',
  `support-ssl` enum('Yes','No') NOT NULL DEFAULT 'No',
  `apache2-ssl-updated` int(11) NOT NULL DEFAULT '0',
  `awstats-ssl-updated` int(11) NOT NULL DEFAULT '0',
  `online` int(11) NOT NULL DEFAULT '0',
  `staging-cron` varchar(128) NOT NULL DEFAULT '',
  `salt` varchar(64) NOT NULL DEFAULT '',
  `created` int(11) NOT NULL DEFAULT '0',
  `staged` int(11) NOT NULL DEFAULT '0',
  `folders-created` int(11) NOT NULL DEFAULT '0',
  `folders-exist` int(11) NOT NULL DEFAULT '0',
  `folders-deleted` int(11) NOT NULL DEFAULT '0',
  `files-created` int(11) NOT NULL DEFAULT '0',
  `files-exist` int(11) NOT NULL DEFAULT '0',
  `files-deleted` int(11) NOT NULL DEFAULT '0',
  `bytes-files-created` mediumint(28) NOT NULL DEFAULT '0',
  `bytes-files-exist` mediumint(28) NOT NULL DEFAULT '0',
  `bytes-files-deleted` mediumint(28) NOT NULL DEFAULT '0',
  `renegade-created` int(11) NOT NULL DEFAULT '0',
  `renegade-exist` int(11) NOT NULL DEFAULT '0',
  `renegade-deleted` int(11) NOT NULL DEFAULT '0',
  `bytes-renegade-created` mediumint(28) NOT NULL DEFAULT '0',
  `bytes-renegade-exist` mediumint(28) NOT NULL DEFAULT '0',
  `bytes-renegade-deleted` mediumint(28) NOT NULL DEFAULT '0',
  `root-folders` mediumtext,
  `folders-hunted` int(11) NOT NULL DEFAULT '0',
  `files-hunted` int(11) NOT NULL DEFAULT '0',
  `renegade-hunted` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`webdav_id`,`uid`),
  KEY `SEARCH` (`uid`,`key`,`webdav_id`,`username`,`hashinfo`,`support-ssl`,`staging-cron`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
